"""empty message

Revision ID: 01b507fa5dff
Revises: c3b1a66f02e0
Create Date: 2024-06-06 22:28:15.777561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b507fa5dff'
down_revision = 'c3b1a66f02e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('your_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qc', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('img', sa.String(length=200), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('qc_status')
        batch_op.drop_column('serial_number')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('your_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('serial_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('qc_status', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('img')
        batch_op.drop_column('qc')

    # ### end Alembic commands ###
