"""empty message

Revision ID: c3b1a66f02e0
Revises: dc82e8fe0a08
Create Date: 2024-05-29 16:20:08.852997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b1a66f02e0'
down_revision = 'dc82e8fe0a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('your_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('qc_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=False))
        batch_op.drop_column('value')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('your_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('value', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('date_added')
        batch_op.drop_column('image_path')
        batch_op.drop_column('qc_status')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
